# Generated by Django 3.2.9 on 2021-12-05 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=200, null=True)),
                ('Branch', models.CharField(max_length=200, null=True)),
                ('Course', models.CharField(max_length=200, null=True)),
                ('Year', models.CharField(max_length=200, null=True)),
                ('Type_of_complaint', models.CharField(choices=[('ClassRoom', 'ClassRoom'), ('Teacher', 'Teacher'), ('Security', 'Security'), ('Health&Hygiene', 'Health&Hygiene'), ('HostelMess', 'HostelMess'), ('Academics', 'Academics')], max_length=200, null=True)),
                ('Description', models.TextField(max_length=4000, null=True)),
                ('DriveLink', models.URLField(max_length=400)),
                ('Time', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Closed'), (2, 'Registered'), (3, 'Pending')], default=3)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
