# Generated by Django 3.2.9 on 2021-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Branch',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Ceramic', 'Ceramic'), ('Chemical', 'Chemical'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Metallurgical', 'Metallurgical'), ('Mining', 'Mining'), ('Pharmaceutical', 'Pharmaceutical')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('IDD', 'IDD'), ('M.Tech', 'M.Tech')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('Security', 'Security'), ('Health&Hygiene', 'Health&Hygiene'), ('HostelMess', 'HostelMess'), ('Academics', 'Academics'), ('Council', 'Council'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=200, null=True),
        ),
    ]
